apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
  database: {{ .Values.auth.database }}
