apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres
spec:
  selector:
    matchLabels:
      app: keycloak-postgres
  serviceName: keycloak-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc
