apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  admin-username: {{ .Values.admin.username }}
  admin-password: {{ .Values.admin.password }}
  db-username: {{ .Values.db.username }}
  db-password: {{ .Values.db.password }}
