image:
  repository: ghcr.io/suki-yo/cookie-api
  tag: "main-956e927d82385fed6ebce81e9ebd1994bc356d07"
replicas: 1
service:
  port: 3000
env:
  pgHost: cookie-postgres
  pgPort: 5432
  pgDatabase: cookie
  pgUser: cookie
  pgPassword: cookie
