image:
  repository: ghcr.io/suki-yo/cookie-api
  tag: "main-4b304c75f701532410bf8ff02cc6db61bd2aaf0e"
replicas: 1
service:
  port: 3000
env:
  pgHost: cookie-postgres
  pgPort: 5432
  pgDatabase: cookie
  pgUser: cookie
  pgPassword: cookie
