image:
  repository: ghcr.io/suki-yo/cookie-api
  tag: "main-e17057110b0f55f0dcb9ed89eb1ce91dfcdd82e4"
replicas: 1
service:
  port: 3000
env:
  pgHost: cookie-postgres
  pgPort: 5432
  pgDatabase: cookie
  pgUser: cookie
  pgPassword: cookie
